kind: Template
apiVersion: v1
template: whirlwind-caravan
metadata:
  name: whirlwind-caravan
objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: whirlwind-caravan
    labels:
      name: whirlwind-caravan
  spec:
    ports:
      - name: spark-port
        protocol: TCP
        port: 4040
        targetPort: 4040
    selector:
      name: whirlwind-caravan

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: whirlwind-caravan
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - whirlwind-caravan
          from:
            kind: ImageStreamTag
            name: whirlwind-caravan:latest
    replicas: 1
    selector:
      name: whirlwind-caravan
    template:
      metadata:
        labels:
          name: whirlwind-caravan
      spec:
        containers:
          - name: whirlwind-caravan
            image: ${WHIRLWIND_CARAVAN_IMAGE}
            env:
              - name: WHIRLWIND_CARAVAN_MONGO_URL
                value: ${MONGO_URL}
              - name: WHIRLWIND_CARAVAN_REST_URL
                value: ${REST_URL}
              - name: WHIRLWIND_CARAVAN_SPARK_MASTER
                value: ${SPARK_MASTER}
              - name: WHIRLWIND_CARAVAN_SOCKET
                value: ${DATA_SOCKET}
              - name: SPARK_USER
                value: ${SPARK_USER}

parameters:
- name: WHIRLWIND_CARAVAN_IMAGE
  description: Full name of the whirlwind caravan image
  value: docker.io/elmiko/whirlwind-caravan
- name: MONGO_URL
  description: URL for the mongo db
  required: true
- name: REST_URL
  description: URL to the rest endpoint for writing data
  required: true
- name: SPARK_MASTER
  description: Location of the spark master
  required: true
- name: DATA_SOCKET
  description: Location of the data socket to connect
  required: true
- name: SPARK_USER
  description: a spark user for the cluster
  value: somesparkuser
